import { toast } from "sonner";
import { Link } from "@tanstack/react-router";
import type { WardAdvisory, WardRisk } from "@/data/wards";
import { RiskBadge } from "./RiskBadge";
import { cn } from "@/lib/utils";

export function AdvisoryCard({
  ward,
  advisory,
  compact = false,
  className,
}: {
  ward: WardRisk;
  advisory: WardAdvisory;
  compact?: boolean;
  className?: string;
}) {
  return (
    <article className={cn("panel overflow-hidden", className)}>
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-surface-2/70 px-4 py-3">
        <div>
          <h3 className="label-mono text-foreground">Public Health Advisory</h3>
          <p className="mt-1 text-xs text-muted-foreground">
            {ward.ward_name} · Coimbatore Municipal Corporation
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="rounded border border-border px-2 py-0.5 font-mono text-[10px] tracking-widest text-muted-foreground">
            PRIORITY {advisory.priority}
          </span>
          <RiskBadge level={ward.risk_level} />
        </div>
      </header>

      <div className="space-y-4 px-4 py-4">
        <div>
          <div className="label-mono">Reason</div>
          <p className="mt-1.5 text-sm leading-relaxed text-foreground/90">{advisory.reason}</p>
        </div>

        <div>
          <div className="label-mono">Recommended action</div>
          <ul className="mt-1.5 space-y-1.5">
            {advisory.recommended_action.map((a) => (
              <li key={a} className="flex gap-2.5 text-sm text-foreground/90">
                <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-risk-high" />
                <span>{a}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-border pt-3">
          <div>
            <div className="label-mono">Review status</div>
            <div className="mt-1 font-mono text-xs text-risk-moderate">{advisory.review_status}</div>
          </div>
          <div>
            <div className="label-mono">Source</div>
            <div className="mt-1 text-xs text-muted-foreground">
              Generated by Gemini LLM from model risk + SHAP factors
            </div>
          </div>
        </div>

        <p className="rounded border border-border bg-surface-2/60 px-3 py-2 text-[11px] text-muted-foreground">
          Duty officer review required before official release. The advisory text is generated from
          the model&apos;s risk score, forecast WBGT and SHAP factors — the language model does not
          compute the risk.
        </p>

        {!compact && (
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() =>
                toast.success(`Alert prepared for ${ward.ward_name}`, {
                  description: "Status: READY TO ISSUE — demo only, no message dispatched.",
                })
              }
              className="rounded-md bg-risk-extreme px-4 py-2 text-sm font-medium text-background transition-opacity hover:opacity-90"
            >
              ISSUE ALERT
            </button>
            <button
              onClick={() =>
                toast(`Added to response plan`, {
                  description: `${ward.ward_name} queued in the Action Center (demo).`,
                })
              }
              className="rounded-md border border-border-strong px-4 py-2 text-sm font-medium transition-colors hover:bg-accent"
            >
              ADD TO RESPONSE PLAN
            </button>
            <Link
              to="/actions"
              className="rounded-md px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              Open Action Center →
            </Link>
          </div>
        )}
      </div>
    </article>
  );
}
